name: main workflow
on: 
  push:
     branches:
      - main
  pull_request:
     branches:
      - main
env:
  docker_username: nima-moayedzadeh
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
    Build:
      runs-on: ubuntu-latest
      container: golang:1.25.0-bookworm
      steps:
        - name: Clone down repository
          uses: actions/checkout@v5
        - name: Build backend
          run: |
            cd backend
            go build
        - name: Build frontend
          run: |
            cd ../frontend
            go build
        - name: Run test
          run: go test
          
      

    
