name: Main workflow
on: 
  push:
     branches:
      - main
  pull_request:
     branches:
      - main
env:
  docker_username: nima-moayedzadeh
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
    Build:
      runs-on: ubuntu-latest
      container: golang:1.25.0-bookworm
      steps:
        - name: Clone down repository
          uses: actions/checkout@v5
        - name: Build backend
          run: |
            cd backend
            go build -buildvcs=false
        - name: Build frontend
          run: |
            cd frontend
            go build -buildvcs=false
        - name: Run test
          run: | 
            cd frontend
            go test

    Docker-build-and-push:
        runs-on: ubuntu-latest
        needs: [Build]
        permissions:
          packages: write
        steps:
          - name: Clone down repository
            uses: actions/checkout@v5
          - name: Login to DockerHub
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
          - name: Build and push frontend
            uses: docker/build-push-action@v5
            with:
              context: ./frontend
              push: true
              tags: ghcr.io/${{ github.actor }}/cookie-frontend:latest
          - name: Build and push backend
            uses: docker/build-push-action@v5
            with:
              context: ./backend
              push: true
              tags: ghcr.io/${{ github.actor }}/cookie-backend:latest
          

          
      

    
